name: dswitch
version: 7.0.0
homepage: https://dswitch.onepub.dev
documentation: https://dswitch.onepub.dev
description: DSwitch is a cli tool that allows you to rapidly switch between channels and versions of Dart. You can also pin a channel to a specific version.
repository: https://github.com/onepub-dev/dswitch
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  archive: ^4.0.7
  args: ^2.1.1
  dcli: ^8.2.0
  dcli_core: ^8.0.0
  dcli_terminal: ^8.0.0
  meta: ^1.0.0
  path: ^1.0.0
  pub_semver: ^2.0.0
  pubspec_manager: ^3.0.1
  scope: ^5.1.0
  settings_yaml: ^8.0.1
  system_info2: ^4.0.0
  win32: ^5.3.0
dev_dependencies:
  lint_hard: ^6.2.1
  mocktail: ^1.0.2
  test: ^1.15.0
executables:
  dswitch:
  dswitch_install:
